name: hipster
description: "A Flutter video calling application with authentication and user management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # HTTP and API
  http: ^1.1.0
  
  # Local Storage and Caching
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # UI Components
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utils
  path: ^1.8.3
  zego_uikit_prebuilt_call: ^4.18.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/