name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    name: Analyze, Test, Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub

      - name: Build Android APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  # iOS/macOS builds require macOS runners and signing; uncomment to enable
  # build-ios:
  #   name: Analyze, Test, (Optional) Build iOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: 'stable'
  #         cache: true
  #     - name: Flutter Pub Get
  #       run: flutter pub get
  #     - name: Analyze
  #       run: flutter analyze
  #     - name: Run tests
  #       run: flutter test --no-pub
  #     # Building iOS requires signing; configure certificates/profiles before enabling:
  #     # - name: Build iOS
  #     #   run: flutter build ipa --no-codesign

